### ISSUE TITLE
ImportError: /usr/lib/libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl13is_contiguousENS_12MemoryFormatE

### ISSUE THREAD

**Issue by JachinMa** [opencv/openvino_training_extensions#291] opened 2020-05-04 07:07 UTC
I was trying to train the model using the command:
python ../../external/mmdetection/tools/train.py          $CONFIGURATION_FILE

but faced this preoblem:
python ../../external/mmdetection/tools/train.py          $CONFIGURATION_FILE
Traceback (most recent call last):
  File "../../external/mmdetection/tools/train.py", line 8, in <module>
    from mmdet.datasets import get_dataset
  File "/home/j/Desktop/mmdetection/mmdet/datasets/__init__.py", line 2, in <module>
    from .cityscapes import CityscapesDataset
  File "/home/j/Desktop/mmdetection/mmdet/datasets/cityscapes.py", line 14, in <module>
    from .coco import CocoDataset
  File "/home/j/Desktop/mmdetection/mmdet/datasets/coco.py", line 10, in <module>
    from mmdet.core import eval_recalls
  File "/home/j/Desktop/mmdetection/mmdet/core/__init__.py", line 7, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/j/Desktop/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/j/Desktop/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/j/Desktop/mmdetection/mmdet/ops/__init__.py", line 11, in <module>
    from .nms import nms, soft_nms
  File "/home/j/Desktop/mmdetection/mmdet/ops/nms/__init__.py", line 1, in <module>
    from .nms_wrapper import nms, soft_nms
  File "/home/j/Desktop/mmdetection/mmdet/ops/nms/nms_wrapper.py", line 4, in <module>
    from . import nms_cpu, nms_cuda
ImportError: /usr/lib/libtorch_cpu.so: undefined symbol: _ZNK3c1010TensorImpl13is_contiguousENS_12MemoryFormatE

my gpu is 1060,cuda 10.2,torch 1.1.

can anyone help with my preoblem?I cant find proper answer.

thx

**Comment by druzhkov-paul** [comment] 2020-05-04 07:49
@JachinMa PyTorch 1.1 might be too old. The code is tested with PyTorch 1.4. Also please make sure that buildtime and runtime versions match.

**Comment by JachinMa** [comment] 2020-05-04 08:05
> @JachinMa PyTorch 1.1 might be too old. The code is tested with PyTorch 1.4. Also please make sure that buildtime and runtime versions match.

thx for reply

I used pytorch1.5 at first,and faced this problem:
ImportError: cannot import name 'deform_conv_cuda'

Traceback (most recent call last):
  File "../../external/mmdetection/tools/train.py", line 8, in <module>
    from mmdet.datasets import get_dataset
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/datasets/__init__.py", line 1, in <module>
    from .custom import CustomDataset
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/datasets/custom.py", line 11, in <module>
    from .extra_aug import ExtraAugmentation
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/datasets/extra_aug.py", line 5, in <module>
    from mmdet.core.evaluation.bbox_overlaps import bbox_overlaps
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/core/__init__.py", line 6, in <module>
    from .post_processing import *  # noqa: F401, F403
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/core/post_processing/__init__.py", line 1, in <module>
    from .bbox_nms import multiclass_nms
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/core/post_processing/bbox_nms.py", line 3, in <module>
    from mmdet.ops.nms import nms_wrapper
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/ops/__init__.py", line 1, in <module>
    from .dcn import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .functions.deform_conv import deform_conv, modulated_deform_conv
  File "/home/j/Desktop/openvino_training_extensions-develop/external/mmdetection/mmdet/ops/dcn/functions/deform_conv.py", line 5, in <module>
    from . import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'

this will not happen in pytorch1.1,maybe I should use pytorch 1.4?

also,this question may be stupid,but what is buildtime and runtime,I am new here.

**Comment by druzhkov-paul** [comment] 2020-05-04 12:08
PyTorch 1.5 support is not there yet. Some components may be compatible with multiple versions, but full functionality is only guaranteed for PyTorch 1.4 currently. So please try it.

In general the simplest way to set everything up properly is to closely follow install instructions from [here](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_detection/README.md#installation).

**Comment by JachinMa** [comment] 2020-05-05 03:00
> PyTorch 1.5 support is not there yet. Some components may be compatible with multiple versions, but full functionality is only guaranteed for PyTorch 1.4 currently. So please try it.
> 
> In general the simplest way to set everything up properly is to closely follow install instructions from [here](https://github.com/opencv/openvino_training_extensions/blob/develop/pytorch_toolkit/object_detection/README.md#installation).

py1.4 did work,now I wont see this problem,but another problem occurs:

Traceback (most recent call last):
  File "../../external/mmdetection/tools/train.py", line 8, in <module>
    from mmdet.datasets import get_dataset
ImportError: cannot import name 'get_dataset'

I cant find the file 'get_dataset.py' everywhere,what should I do to solve this?

**Comment by druzhkov-paul** [comment] 2020-05-06 08:36
Please make sure that submodules are up to date. Use this command to update all submodules:
```shell
git submodule update --init
```

**Comment by druzhkov-paul** [comment] 2020-05-13 07:48
@JachinMa Did submodules' update help?

**Comment by JachinMa** [comment] 2020-05-13 08:03
> @JachinMa Did submodules' update help?

sorry I forgot to reply.

I've tried this comman,but it didnt work.

now I get another experiment to run,Im very glad of your kind help.

**Comment by druzhkov-paul** [comment] 2020-05-21 09:46
@JachinMa As long as I can't reproduce the issue on my side, at least without some extra information from you, I'll close it now. If you'll experience it again, please, reopen.

**Closed by druzhkov-paul** 2020-05-21 09:46 UTC
Labels: question
